### ISSUE TITLE
issue docker 18.09.0 build 4d60db4

### ISSUE THREAD

**Issue by antwal** [mal/docker-for-mac-host-bridge#11]
Install log:

Install tuntap kernel extension
Password:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer: The install was successful.
Ensure tap extension is loaded
Permit non-root usage of tap1 device
./install.sh: line 60: pushd: /Applications/Docker.app/Contents/Resources/bin: No such file or directory

**Comment by antwal** [comment]
My docker path is /Applications/Developer/Docker.app but it not working

Move original com.docker.hyperkit
Install com.docker.hyperkit shim
-- RESTART DOCKER NOW
When docker is responding (i.e. docker image ls), press return: 
Create host-accessible network
ef5f84b1c6ffa88477cf77d2490bbf43104729398eb9041712e3bb510b666ca2
Bridge tap into docker network
./install.sh: line 111: /Users/antwal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty: No such file or directory

the folder com.docker.driver.amd64-linux not exist in path

**Comment by antwal** [comment]
I have tried fix it, the path of tty in this version is : `$HOME/Library/Containers/com.docker.docker/Data/vms/0/tty`

the script working and i have tap1 interface:

```
tap1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 4e:c9:c1:15:23:99 
	inet 172.18.0.1 netmask 0xffff0000 broadcast 172.18.255.255
	media: autoselect
	status: active
	open (pid 33858)
```

but not working:

```
docker container run -d --net acme --rm nginx:alpine
Unable to find image 'nginx:alpine' locally
alpine: Pulling from library/nginx
4fe2ade4980c: Already exists 
2963b79251cb: Pull complete 
8ce2a7ad052e: Pull complete 
8571e73c6abf: Pull complete 
Digest: sha256:fde4efa0cd493b7851221377426423583fc9003179eb92b5c3cf2288046ade73
Status: Downloaded newer image for nginx:alpine
d10c53271ef502075492d1f3dad8d98cd32d17f62e50c88f81227181ab667e45

docker container inspect -f '{{.NetworkSettings.Networks.acme.IPAddress}}' $(docker ps -qa)
172.18.0.2

wget 172.18.0.2
--2018-12-19 13:53:11--  http://172.18.0.2/
Connecting to 172.18.0.2:80... ^C

ping 172.18.0.2
PING 172.18.0.2 (172.18.0.2): 56 data bytes
ping: sendto: Host is down
ping: sendto: Host is down
Request timeout for icmp_seq 0
^C
--- 172.18.0.2 ping statistics ---
2 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by Tianny** [comment]
> I have tried fix it, the path of tty in this version is : `$HOME/Library/Containers/com.docker.docker/Data/vms/0/tty`
> 
> the script working and i have tap1 interface:
> 
> ```
> tap1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
> 	ether 4e:c9:c1:15:23:99 
> 	inet 172.18.0.1 netmask 0xffff0000 broadcast 172.18.255.255
> 	media: autoselect
> 	status: active
> 	open (pid 33858)
> ```
> 
> but not working:
> 
> ```
> docker container run -d --net acme --rm nginx:alpine
> Unable to find image 'nginx:alpine' locally
> alpine: Pulling from library/nginx
> 4fe2ade4980c: Already exists 
> 2963b79251cb: Pull complete 
> 8ce2a7ad052e: Pull complete 
> 8571e73c6abf: Pull complete 
> Digest: sha256:fde4efa0cd493b7851221377426423583fc9003179eb92b5c3cf2288046ade73
> Status: Downloaded newer image for nginx:alpine
> d10c53271ef502075492d1f3dad8d98cd32d17f62e50c88f81227181ab667e45
> 
> docker container inspect -f '{{.NetworkSettings.Networks.acme.IPAddress}}' $(docker ps -qa)
> 172.18.0.2
> 
> wget 172.18.0.2
> --2018-12-19 13:53:11--  http://172.18.0.2/
> Connecting to 172.18.0.2:80... ^C
> 
> ping 172.18.0.2
> PING 172.18.0.2 (172.18.0.2): 56 data bytes
> ping: sendto: Host is down
> ping: sendto: Host is down
> Request timeout for icmp_seq 0
> ^C
> --- 172.18.0.2 ping statistics ---
> 2 packets transmitted, 0 packets received, 100.0% packet loss
> ```

Have you alreay fixed it?
