### ISSUE TITLE
Support for 19.03

### ISSUE THREAD

**Issue by tanasecosminromeo** [mal/docker-for-mac-host-bridge#12]
Any change you can help with support for 18.03 ?

**Comment by mal** [comment]
Afraid I'm no longer in a position to be able to help with this, however another project that may be of interest to you and seeks to do a similar thing can be found [here](https://github.com/AlmirKadric-Published/docker-tuntap-osx). As far as I know, it is still maintained and is seeking out alternatives to tuntap in light of it's proposed sunsetting. Best of luck!

**Comment by tanasecosminromeo** [comment]
Hi @tanasecosminromeo thank you for the quick reply and suggestion. Using your suggestion I've managed to solve my issue. Pity something as _basic_ as bridge networks don't work by default on docker for mac, thanks a lot both for your project and your suggestion!
