### ISSUE TITLE
interface tap1 does not exist

### ISSUE THREAD

**Issue by murtyjones** [mal/docker-for-mac-host-bridge#6]
Hi -

I cloned this repository down in an attempt to install it. Unfortunately, it errors out at this point:
```
Bridge tap into docker network
Assign the network gateway IP to the tap interface
**ifconfig: interface tap1 does not exist**
```

Has anyone fixed this previously?

macOS Sierra (10.12.6)
Docker version:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mal** [comment]
**Does `/dev/tap1` exist on your system?**
If not try visiting and installing `tuntaposx` following their instructions and then try again.

**Do you always see the message "Install tuntap kernel extension" when running `install.sh`?**
This suggests that the `tuntaposx` driver is either not installed, or not being recognised as a character device (read on).

**Is `/dev/tap1` correctly identified as a character device?**
Test this by running: `test -c /dev/tap1; echo $?`, you're hoping for a `0`. If you see something else but `/dev/tap1` exists, try:

1. Remove [this line](https://github.com/mal/docker-for-mac-host-bridge/blob/7ba27b77f067f52de0a1f12dcb758627c387c4bb/install.sh#L16) from `install.sh`
2. Run `install.sh` again (failure expected)
3. Restart Docker via the tray
4. Run `install.sh` again (hopefully success)

**Comment by murtyjones** [comment]
Hey, thanks for the quick reply. 

Looks like /dev1/tap1 exists/ and is identified as a character device.

**Comment by mal** [comment]
Could you try doing just steps 3 and 4 and see if that helps? It's possible docker did not activate the tap1 interface or that you missed the restart docker prompt on your inital run of `install.sh`.
