### ISSUE TITLE
Bridge doesn't installed on edge version 18.05.0-ce-mac67

### ISSUE THREAD

**Issue by artemkaint** [mal/docker-for-mac-host-bridge#9]
Version 18.05.0-ce-mac67 (25042)

Plugin is successfully installed, but host doesn't have access to docker network

```
Bridge tap into docker network
Assign the network gateway IP to the tap interface
```

**Comment by mal** [comment]
My situation has changed (I've convinced my team to move wholesale to linux!) so it's unlikely I'll be maintaining this going forward. There is a project with similar goals but a more involved approach [here](https://github.com/AlmirKadric-Published/docker-tuntap-osx) that may be of interest, and/or if you or anyone else is interested in maintaining this project I can facilitate that.
